# Generated by Django 6.0.5 on 2026-05-12 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('final_answer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_iterations', models.IntegerField(default=0)),
                ('total_tool_calls', models.IntegerField(default=0)),
                ('token_usage', models.IntegerField(default=0, help_text='Total tokens used')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='repositories.repository')),
            ],
            options={
                'db_table': 'research_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('line_start', models.IntegerField(blank=True, null=True)),
                ('line_end', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(help_text="Agent's insight or observation")),
                ('relevance_score', models.FloatField(default=0.0, help_text='How relevant this finding is (0-1)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='research_sessions.researchsession')),
            ],
            options={
                'db_table': 'findings',
                'ordering': ['-relevance_score', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_input', models.JSONField()),
                ('tool_output', models.TextField()),
                ('iteration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('execution_time_ms', models.IntegerField(default=0, help_text='Execution time in milliseconds')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='research_sessions.researchsession')),
            ],
            options={
                'db_table': 'tool_calls',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['repository', '-created_at'], name='research_se_reposit_42c5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['status'], name='research_se_status_60099e_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['session', '-relevance_score'], name='findings_session_1631d4_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['session', 'created_at'], name='tool_calls_session_a0118e_idx'),
        ),
        migrations.AddIndex(
            model_name='toolcall',
            index=models.Index(fields=['tool_name'], name='tool_calls_tool_na_b205bd_idx'),
        ),
    ]
