# Generated by Django 6.0.5 on 2026-05-12 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=500, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_analyzed', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_sessions', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
                'ordering': ['-last_analyzed'],
                'indexes': [models.Index(fields=['url'], name='repositorie_url_d7d6d5_idx'), models.Index(fields=['-last_analyzed'], name='repositorie_last_an_ffa979_idx')],
            },
        ),
    ]
